
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.19"

[[constraint]]
  name = "github.com/cockroachdb/cockroach"
  branch = "master"
  source = "https://github.com/jgraettinger/cockroach-encoding.git"


# bbolt is a transitive dependency from coreos/etcd. At this time, the current
# version of etcd (v3.3.2) has a dependency on this version of bbolt which is
# not part of etcd's Gopkg.toml.
[[override]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.6"


[[constraint]]
  name = "github.com/pkg/sftp"
  version = "1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/tecbot/gorocksdb"
  revision = "736494885839fb191f59399d9c572a4fbf1b9f9e"
  source = "https://github.com/LiveRamp/gorocksdb.git"

[[constraint]]
  name = "github.com/youtube/vitess"
  version = "2.1.1"

